language: node_js
node_js:
  - 12.16.2
services:
  - docker
deploy:
  # Build Docker container and push to Docker Hub
  provider: script
  script: bash scripts/ci_docker_push.sh
  on:
    branch: master
